name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  inherited_stream:
    path: ../
  rxdart: ^0.28.0

flutter:
  uses-material-design: true
